version: '3.3'

services:
  dbdevelopment:
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbvol:/etc/mysql

volumes:
  dbvol:
